name: Automated review

permissions:
  contents: read
  pull-requests: write
  id-token: write # This is required for requesting the JWT

on:
  pull_request_target:
  pull_request_review_comment:
    types: [created]

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

env:
  TARGET_AWS_REGION: us-east-1
jobs:
  Run-Bedrock-review:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: gha-session
          aws-region: ${{ env.TARGET_AWS_REGION }}
      - name: PR review
        uses: tmokmss/bedrock-pr-reviewer@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          debug: true
          language: ja-JP
          review_simple_changes: false
          review_comment_lgtm: false
          only_allow_collaborator: true
          path_filters: |
            **/*.{md,ts,tsx}
          summarize_release_notes: |
            PullRequest のコード差分を読んで、変更内容の概要がわかるように100文字程度にまとめてください。内容はソフトウェアエンジニアが読んで分かりやすいものにしてください。
          review_file_diff: |
            あなたは一流のソフトウェアエンジニアです。コードの差分が入力されるので、<rules></rules>に従ってコードレビューをしてください。
            <rules>
            - コードに改善点がない場合は、コメントしないでください。「このコードは適切です」などといったコメントは一切不要です。
            - 関数名と実装内容があっていない場合は、指摘してください。
            - セキュリティ的に脆弱なコードの場合は、指摘してください。
            - 意味のないコード、意味のないコメントが含まれている場合は指摘してください。
            - よりシンプルに実装できるもの、一般的な設計から外れる実装などの保守性に問題のあるコードの場合は、指摘してください。
            - レビュー対象がドキュメントの場合、わかりやすい日本語になっているか、誤解の余地がある表現になっていれば、指摘してください。
            </rules>
